### PR TITLE
Passively wait for mpd to send events for updates

### LINKED ISSUE #24: Compatibility with `playerctld`
Hi, I use this program with couple of other media players as well. 
Playerctld is a feature introduced to detect the "last active player".
I was wondering if mpd-mpris is compatible with that.

### PR DESCRIPTION
**Pull request by natsukagami**
We basically use `mpd`'s `idle` command to wait for updates to fire our own `Status` update.

`-interval` is no longer needed, since we're not polling anymore.

Should resolve #24.

### CODE REVIEW

**Comment by natsukagami** [comment]
@cdown @Barbaross93 I think this is the better approach to go forward (no polling). What do you think?

**Comment by natsukagami** [comment]
That’s interesting - in theory a metadata request should force mpd-mpris to
update its own status… or I might have forgotten to do that ;(

Chris Down ***@***.***> schrieb am Mo. 27. März 2023 um 7:54
PM:

**Comment by natsukagami** [comment]
Nevermind, I got it wrong in my head too. MPRIS wants the Position (seek)
property to be kept correct at all time, but not broadcasted when they are
updated. It seems that I have got it wrong from the beginning ;) I probably
will keep an internal clock on my own to keep track of seek as well.

Natsu Kagami ***@***.***> schrieb am Mo. 27. März 2023 um 8:19
PM:

**Comment by natsukagami** [comment]
It works fine to me atm, so I'm gonna merge this one :) If anything breaks feel free to open another issue!

**Comment by Barbaross93** [comment]
I apologize for not responding sooner. I'm not able to test it at this time, but any time were we don't depend on polling is always a huge plus in my book!

**Comment by cdown** [comment]
Yeah agreed, as long as stuff works, I'm in favour of the concept. Thank you for working on this!

**Pull request merged**
