### PR TITLE
Add Openrc Service File

### LINKED ISSUE #48: Add OpenRC Service
I think that mpd-mpris should include a service file for OpenRC to make setup convenient for OpenRC users. I will work on creating the service.

### PR DESCRIPTION
**Pull request by unrealapex**
Closes #48

### CODE REVIEW

**Comment by natsukagami** [comment]
Thanks! I never used OpenRC and probably won't be using it in the near future, so I don't really feel comfortable maintaining this service file.

That said I think I will merge this, as it's useful to have even as a starter for someone who needs :)

**Review by natsukagami — APPROVED** [review]

**Comment by unrealapex** [comment]
Thank you! I am willing to maintain the service file if any issues arise.

**Comment by unrealapex** [comment]
Do you think the service script should have an extension or be named differently to denote that it is an OpenRC service file? I think renaming the file to `mpd-mpris-openrc-service` would be more descriptive.

**Comment by natsukagami** [comment]
> Do you think the service script should have an extension or be named differently to denote that it is an OpenRC service file? I think renaming the file to mpd-mpris-openrc-service would be more descriptive.

I think it's fine the way it is if it's the standard way to name things in the OpenRC world. 
Otherwise, I think the better solution is to move it under a new directory (`openrc/mpd-mpris-service`) or something like that. It's probably the nicer thing to do, since users can then just do a `cp` of the file to the right location... like how you can do it with the systemd unit.

If you're open to do so, maybe you can move the systemd unit file to a `systemd/` directory as well :pray:

**Comment by unrealapex** [comment]
The standard name would just be the name of the service, however, when building the project the service file is overwritten by the executable of the same name.

> If you're open to do so, maybe you can move the systemd unit file to a systemd/ directory as well 🙏

I think that would be a good idea.

> Otherwise, I think the better solution is to move it under a new directory (openrc/mpd-mpris-service) or something like that

How do you feel about having a `services` directory and moving both files there?

**Comment by natsukagami** [comment]
Sure, that works :)

**Pull request merged**
